### ISSUE TITLE
Style clean up with filters

### ISSUE THREAD

**Issue by TerryMooreII** [joeeames/ngDocIO_Issues#3]
Add some margin and a larger touch point for removing selected filters.  Plus this is a lot of blue, imho

<img width="345" alt="screen shot 2017-04-24 at 1 24 35 pm" src="https://cloud.githubusercontent.com/assets/602825/25349960/856babc4-28f1-11e7-9725-f337c0eedea0.png">

**Comment by joeeames** [comment]
I asked @alyssamichelle to look at this.

**Comment by alyssamichelle** [comment]
Thanks @TerryMooreII ! I'm aware of these UI issues and will tackle them soon.

**Comment by alyssamichelle** [comment]
My latest updates to master should fix these issues! They should be in prod soon :)

**Comment by TerryMooreII** [comment]
Cool, I will keep an eye out

**Comment by TerryMooreII** [comment]
There is still an issue with the last tags and the reset filter button butting up against each other.  Also now that the them is black the blue spinner looks strange.

**Comment by joeeames** [comment]
I haven't pushed up the changes she did yet.

**Comment by TerryMooreII** [comment]
Oh, sorry, I assumed you did since the theme changed.

**Comment by joeeames** [comment]
pushed up a bit ago.
